version: '3'
services:
  master:
    image: mysql:5.7
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./config/master.cnf:/etc/mysql/conf.d/master.cnf
    networks:
      web_net:
        ipv4_address: 192.168.99.11
  slave:
    image: mysql:5.7
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./config/slave.cnf:/etc/mysql/conf.d/slave.cnf
    networks:
      web_net:
        ipv4_address: 192.168.99.12
  go:
      links:
        - master
        - slave
      build:
        context: "./"
      tty: true
      ports:
        - 8095:8081
      volumes:
        - "./app/:/go/src/app"
      depends_on:
        - master
        - slave
networks:
  web_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.99.0/25
