version: '3'
services:
  go:
    build:
      context: "./"
    tty: true
    networks:
      mysql_web_net:
        ipv4_address: 192.168.99.13
    ports:
      - 8095:8081
    volumes:
      - "./app/:/go/src/app"
networks:
  mysql_web_net:
    external: true
